services:
  laravel:
    build:
      dockerfile: Dockerfile
    start:
      cmd: php artisan serve --host=0.0.0.0 --port=8080
    env:
      APP_ENV: production
      APP_KEY: ""
      APP_DEBUG: false
      APP_URL: https://saffapi-838cfb0a8bf7c6fe352e6d0a.up.railway.app
      DB_CONNECTION: mysql
      DB_HOST: ${MYSQL_HOST}
      DB_PORT: ${MYSQL_PORT}
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    deploy:
      commands:
        - composer install --no-interaction --prefer-dist --optimize-autoloader
        - php artisan config:clear
        - php artisan key:generate
        - php artisan migrate --force
    domains:
      - your-app-name.up.railway.app
